# Generated by Django 2.2.24 on 2022-04-22 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WikiDescription',
        ),
    ]
