# Generated by Django 2.2.24 on 2021-11-20 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='servicedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
