# Generated by Django 2.2.24 on 2022-04-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_event_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isSuperAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
