# Generated by Django 2.2.24 on 2022-05-01 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_userprofile_issuperadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_events', to='social.Event'),
        ),
    ]
