# Generated by Django 2.2.24 on 2022-05-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_search_searchtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location_name',
            field=models.CharField(default='istanbul', max_length=255),
        ),
    ]
