# Generated by Django 2.2.24 on 2021-12-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20211128_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.TextField(default='Service Name'),
        ),
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.ImageField(blank=True, default='uploads/service_pictures/default.png', null=True, upload_to='uploads/service_pictures/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventcapacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventdescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventname',
            field=models.TextField(default='Event Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventpicture',
            field=models.ImageField(blank=True, default='uploads/event_pictures/default.png', null=True, upload_to='uploads/event_pictures/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
