# Generated by Django 2.2.24 on 2022-05-07 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_service_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='location_name',
            new_name='location_Name',
        ),
    ]
