# Generated by Django 2.2.24 on 2022-05-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_auto_20220507_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='location_Name',
            new_name='city',
        ),
    ]
