# Generated by Django 2.2.24 on 2022-05-07 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_event_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyuser',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tag',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usercomplaints',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userratings',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
