# Generated by Django 2.2.24 on 2022-05-12 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0014_auto_20220507_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomplaints',
            name='adminDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usercomplaints',
            name='isSolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercomplaints',
            name='solutionAction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usercomplaints',
            name='solutionAdmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutionAdmin', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='usercomplaints',
            name='solutionText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
