# Generated by Django 2.2.24 on 2022-05-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_auto_20220512_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='feedbackFactor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='interest',
            name='feedbackGiven',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interest',
            name='feedbackLiked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='implicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interest',
            name='origin',
            field=models.TextField(default='profile'),
        ),
    ]
