# Generated by Django 2.2.24 on 2022-05-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_auto_20220514_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='disapprovedServices',
            field=models.ManyToManyField(blank=True, related_name='disapprovedservices', to='social.Service'),
        ),
    ]
