# Generated by Django 2.2.24 on 2022-05-25 00:43

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_interest_disapprovedservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='city',
            field=models.CharField(blank=True, default='istanbul', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, default='41.0255493,28.9742571', max_length=63, null=True),
        ),
    ]
