# Generated by Django 2.2.24 on 2022-05-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_auto_20220525_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='approvedServices',
            field=models.ManyToManyField(blank=True, related_name='approvedservices', to='social.Service'),
        ),
    ]
