# Generated by Django 2.2.24 on 2021-12-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_auto_20211202_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credithour',
            field=models.IntegerField(default=5),
        ),
    ]
