# Generated by Django 2.2.24 on 2021-12-03 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_auto_20211203_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='service',
            name='servicedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
