# Generated by Django 2.2.24 on 2021-12-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_auto_20211203_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
