# Generated by Django 2.2.24 on 2021-12-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_auto_20211204_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reservehour',
            field=models.IntegerField(default=0),
        ),
    ]
