# Generated by Django 2.2.24 on 2021-12-15 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0023_userprofile_reservehour'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userrating',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='UserRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('rated', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rated', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('rater', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rater', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Service')),
            ],
        ),
    ]
