# Generated by Django 2.2.24 on 2021-12-15 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_auto_20211215_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userratings',
            name='rated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='userratings',
            name='rater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rater', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
