# Generated by Django 2.2.24 on 2021-12-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0025_auto_20211215_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userrating',
        ),
    ]
