# Generated by Django 2.2.24 on 2021-12-25 02:55

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0028_auto_20211224_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='41.0255493,28.9742571', max_length=63),
        ),
    ]
