# Generated by Django 2.2.24 on 2021-12-26 21:31

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0034_eventapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='41.0255493,28.9742571', max_length=63),
        ),
    ]
