# Generated by Django 2.2.24 on 2021-12-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0035_auto_20211226_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
