# Generated by Django 2.2.24 on 2021-12-31 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0036_auto_20211226_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(default='')),
                ('isAccepted', models.BooleanField(default=False)),
                ('offerType', models.TextField(blank=True, null=True)),
                ('offerPk', models.IntegerField(default=0)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('toPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toPerson', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
