# Generated by Django 2.2.24 on 2021-12-31 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0040_auto_20211231_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='relatedTag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatedTag', to='social.Tag', verbose_name='relatedTag'),
        ),
    ]
