# Generated by Django 2.2.24 on 2021-12-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0041_service_relatedtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='relatedTag',
            new_name='tag',
        ),
    ]
