# Generated by Django 2.2.24 on 2021-12-31 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0042_auto_20211231_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='tag',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='social.Tag', verbose_name='category'),
        ),
    ]
