# Generated by Django 2.2.24 on 2021-12-31 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0044_remove_tag_isaccepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='offerPk',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='offerType',
        ),
    ]
