# Generated by Django 2.2.24 on 2022-03-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0047_auto_20220318_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
    ]
