# Generated by Django 2.2.24 on 2022-03-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0048_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
