# Generated by Django 2.2.24 on 2022-03-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0049_auto_20220325_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
