# Generated by Django 2.2.24 on 2022-03-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0050_tag_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='affectedItemId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='affectedItemType',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userratings',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.Service'),
        ),
    ]
