# Generated by Django 2.2.24 on 2022-03-25 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0051_auto_20220325_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='toPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toPerson', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
