# Generated by Django 2.2.24 on 2022-03-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0052_auto_20220325_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='isDeleted',
        ),
    ]
