# Generated by Django 2.2.24 on 2022-03-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0053_remove_tag_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
