# Generated by Django 2.2.24 on 2022-03-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0053_remove_tag_isdeleted'),
        ('social', '0048_remove_service_created_at'),
    ]

    operations = [
    ]
