# Generated by Django 2.2.24 on 2022-03-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0054_merge_20220327_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_city',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
    ]
