# Generated by Django 2.2.24 on 2022-04-02 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0054_auto_20220331_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('itemType', models.TextField(blank=True, null=True)),
                ('itemId', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('communicated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communicated', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
