# Generated by Django 2.2.24 on 2022-04-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0054_auto_20220331_2216'),
        ('social', '0055_auto_20220327_1626'),
    ]

    operations = [
    ]
