# Generated by Django 2.2.24 on 2022-04-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0056_merge_20220401_2334'),
        ('social', '0055_communication'),
    ]

    operations = [
    ]
