# Generated by Django 2.2.24 on 2022-04-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0056_auto_20220412_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='deletionInfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='deletionInfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
