# Generated by Django 2.2.24 on 2022-04-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0059_usercomplaints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomplaints',
            old_name='rated',
            new_name='complainted',
        ),
        migrations.RenameField(
            model_name='usercomplaints',
            old_name='rater',
            new_name='complainter',
        ),
    ]
