# Generated by Django 2.2.24 on 2022-04-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0059_auto_20220403_0317'),
        ('social', '0058_like'),
    ]

    operations = [
    ]
