# Generated by Django 2.2.24 on 2022-04-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0060_merge_20220415_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='wiki_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
