# Generated by Django 2.2.24 on 2022-04-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0060_auto_20220418_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
