# Generated by Django 2.2.24 on 2022-04-21 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0061_auto_20220420_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('operation', models.TextField(blank=True, null=True)),
                ('itemType', models.TextField(blank=True, null=True)),
                ('itemId', models.IntegerField(default=0)),
            ],
        ),
    ]
