# Generated by Django 2.2.24 on 2022-04-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0062_featured'),
        ('social', '0061_service_wiki_description'),
    ]

    operations = [
    ]
