# Generated by Django 2.2.24 on 2022-04-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0062_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='wiki_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
