# Generated by Django 2.2.24 on 2022-04-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0063_merge_20220421_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='wiki_description',
        ),
    ]
