# Generated by Django 2.2.24 on 2022-04-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0063_service_wiki_description'),
        ('social', '0064_remove_service_wiki_description'),
    ]

    operations = [
    ]
