# Generated by Django 2.2.24 on 2022-04-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0065_merge_20220422_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_wiki_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
